//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kharid
    {
        public int ID { get; set; }
        public string KalaName { get; set; }
        public string Day { get; set; }
        public string History { get; set; }
        public long Price { get; set; }
        public string Mounth { get; set; }
    }
}
