//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafeEntities : DbContext
    {
        public cafeEntities()
            : base("name=cafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Kharid> Kharids { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<FormOrder> FormOrders { get; set; }
    }
}
